baseURL = 'https://vinayin.github.io'
languageCode = 'en-us'
title = 'Binay Pradhan'
theme = 'github.com/kaiiiz/hugo-theme-monochrome'
enableEmoji = true
pagination.pagerSize = 5
enableGitInfo = true

[params]
navbar_title = "Binay Kumar Pradhan"
enable_math = true
enable_zooming_js = true
author = "Binay Kumar Pradhan"
footer = "Copyright © 2024 Binay Kumar Pradhan"

[goldmark.renderer]
unsafe= true

[highlight]
anchorLineNos = false
codeFences = false
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noHl = false
noClasses = true
style = "monokai"
tabWidth = 4

[[menu.navbar]]
identifier = "home"
name = "home"
url = "/"
weight = 1

[[menu.navbar]]
identifier = "blog"
name = "blog"
url = "https://wezn.medium.com"
weight = 2

[[menu.navbar]]
identifier = "contact"
name = "contact"
url = "/contact"
weight = 3

[[menu.navbar]]
parent = "contact"
identifier = "Github"
name = "Github"
url = "https://www.github.com/VinayIN"

[[menu.navbar]]
parent = "contact"
identifier = "LinkedIn"
name = "LinkedIn"
url = "https://www.linkedin.com/in/i-binay"
