#!/bin/bash

# Update git information for the Hugo site
# This script generates git information for the latest commit affecting content/home
# Note: In production, this is automatically generated by GitHub Actions

echo "Updating git information for local development..."

# Ensure data directory exists
mkdir -p data

# Generate git info (same command as used in CI/CD)
git --no-pager log -1 --date=iso8601 --pretty=format:'{"commit": "%H", "short_commit": "%h", "date": "%ai", "author": "%an", "subject": "%s"}' -- content/home > data/git_info.json

echo "Git info updated successfully!"
echo "Latest commit info:"
if command -v jq &> /dev/null; then
    cat data/git_info.json | jq '.'
else
    echo "Generated git info JSON:"
    cat data/git_info.json
    echo ""
    echo "Install 'jq' for prettier output: brew install jq"
fi
